-- COLOURS
blk   = "#1a1a1a"
red   = "#b23535"
gre   = "#60801f"
yel   = "#be6e00"
blu   = "#1f6080"
mag   = "#8f46b2"
cya   = "#73afb4"
whi   = "#b2b2b2"
brblk = "#333333"
brred = "#ff4b4b"
brgre = "#9bcd32"
bryel = "#d79b1e"
brblu = "#329bcd"
brmag = "#cd64ff"
brcya = "#9bcdff"
brwhi = "#d2d2d2"
trblk = "#000000"
trwhi = "#ffffff"

-- Pango colour codes
coldef  = "</span>"
colblk  = "<span color='" .. blk .. "'>"
colred  = "<span color='" .. red .. "'>"
colgre  = "<span color='" .. gre .. "'>"
colyel  = "<span color='" .. yel .. "'>"
colblu  = "<span color='" .. blu .. "'>"
colmag  = "<span color='" .. mag .. "'>"
colcya  = "<span color='" .. cya .. "'>"
colwhi  = "<span color='" .. whi .. "'>"
colbblk = "<span color='" .. brblk .. "'>"
colbred = "<span color='" .. brred .. "'>"
colbgre = "<span color='" .. brgre .. "'>"
colbyel = "<span color='" .. bryel .. "'>"
colbblu = "<span color='" .. brblu .. "'>"
colbmag = "<span color='" .. brmag .. "'>"
colbcya = "<span color='" .. brcya .. "'>"
colbwhi = "<span color='" .. brwhi .. "'>"
